# Generated by Django 3.2.6 on 2021-08-21 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название поста')),
                ('content', models.TextField(max_length=10000, verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_posts/', verbose_name='Фото к статье')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('in_archive', models.BooleanField(default=False, verbose_name='В архив')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.blogcategory', verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
